### ISSUE TITLE
TODOs for App Prototype

### ISSUE THREAD

**Issue by flyxiv** [flyxiv/ffxiv_simbot#28]
* [ ] API implementation
   * [x] Axum server implementation https://github.com/flyxiv/ffxiv_simbot/issues/16
   * [x] simulate API https://github.com/flyxiv/ffxiv_simbot/issues/16
   * [x] stat compare API   
   * [ ] advanced Sim API 
   * [ ] best partner API https://github.com/flyxiv/ffxiv_simbot/issues/27
* [x] Finish other job rotations https://github.com/flyxiv/ffxiv_simbot/issues/14
   * [x] implement mana regeneration tick for DRK
* [x] Implement Frontend Application
   * [x] Create SkillId -> Icon Mapping https://github.com/flyxiv/ffxiv_simbot/issues/17 https://github.com/flyxiv/ffxiv_simbot/issues/18
   * [x] Landing Page/Homepage
   * [x] Quicksim Menu
   * [x] Quicksim Result
   * [ ] BestPartner Menu
   * [ ] BestPartner Result

@Essnah12 Add things you want to do before launching prototype(targeting end of July) here.
